name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build site (with staging)
        run: |
          mkdir -p dist/staging

          echo "<h1>PRODUCTION SITE</h1>" > dist/index.html
          echo "<h1>STAGING SITE</h1>" > dist/staging/index.html

          echo "DEBUG OUTPUT:"
          ls -R dist

      - name: Run tests
        run: echo "Running tests..."

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
